# Title: Git Repos
# Description: Git repository URLs and branch settings for all NexusForever components.
# Complexity: Simple

SERVER_BRANCH="expedition-evil-from-the-ether"
SERVER_REPO_URL="https://github.com/NexusForever/NexusForever"

WORLD_DATABASE_BRANCH="master"
WORLD_DATABASE_REPO_URL="https://github.com/NexusForever/NexusForever.WorldDatabase"

PATCHER_BRANCH="master"
PATCHER_REPO_URL="https://github.com/NexusForever/Nexus.Archive"
