# Title: Network
# Description: Server ports, public access settings and firewall configuration.
# Complexity: Simple

# Authentication Server
AUTH_SERVER_PORT="6600"
AUTH_SERVER_PUBLIC=true

# World Server
WORLD_SERVER_PORT="23115"
WORLD_SERVER_PUBLIC=true

# API Server
API_SERVER_PORT="24000"
API_SERVER_PUBLIC=true

# Patcher Server Settings
PATCHER_SERVER_PORT="8080"
PATCHER_SERVER_PUBLIC=true

# Firewall Configuration
ENABLE_FIREWALL=true