# Title: World
# Description: Configuration for the NexusForever World Server
# Complexity: Simple

WORLD_MAXPLAYERS="1000"
WORLD_MOTD="Welcome to this NexusForever server setup with the NexusForever Manager."
WORLD_CROSSFACTIONCHAT="false"
